### ISSUE TITLE
Outdated default port values for ingress and egress?

### ISSUE THREAD

**Issue by jack-bischoff** [greymatter-io/pathogen-greymatter#8]
The service template lists the sidecar's default egress port as 9080 and the ingress port as 8443. To my knowledge, the sidecar's configured defaults for egress and ingress are 10909 and 10808, respectively. 

Is this still true, and should the template default values change to reflect it?

**Comment by jimgaspari** [comment]
This issue looks to be resolved.  The service template has the correct ports listed.
